
server {
	listen 127.0.0.1:8080;
	server_name server_1;

	root /home/xquah/Desktop/webserv/42-webserv;

	error_page 400 /error_page/400.html;
	error_page 401 /error_page/401.html;
	error_page 403 /error_page/403.html;
	error_page 404 /error_page/404.html;
	error_page 405 /error_page/405.html;
	error_page 413 /error_page/413.html;
	error_page 500 /error_page/500.html;
	error_page 501 /error_page/501.html;
	error_page 504 /error_page/504.html;
	error_page 505 /error_page/505.html;

	client_body_size_buf 10000000;

	#test root/index
	location / {
		root /home/xquah/Desktop/webserv/42-webserv;
		index html/sample.html;
		methods GET POST;
	}

	#test alias
	location /test1 {
		alias /home/xquah/Desktop/webserv/42-webserv;
		methods GET POST;
	}

	location /upload {
		alias /home/xquah/Desktop/webserv/42-webserv;
		index html/upload.html;
		methods GET POST;
	}

	location /redirect {
		return 301 https://www.youtube.com;
		methods GET;
	}

	location /auto {
		alias /home/xquah/Desktop/webserv/42-webserv/;
		autoindex on;
		methods GET;
	}

	location /cgi-bin {
		alias /home/xquah/Desktop/webserv/42-webserv/cgi-bin;
		methods GET POST DELETE;
	}
}

server {
	listen 127.0.0.1:8080;
	server_name server_2;

	error_page 404 /error_page/404.html;
	client_body_size_buf 100000000;

	location / {
		root /home/xquah/Desktop/webserv/42-webserv;
		index html/sample2.html;
		autoindex on;
		methods GET POST ;
	}
}

server {
	listen 127.0.0.1:2323;
	#server_name server_1;

	root /home/xquah/Desktop/webserv/42-webserv;

	error_page 404 /error_page/404.html;
	client_body_size_buf 100000000;

	location / {
		root /home/xquah/Desktop/webserv/42-webserv;
		index html/upload.html;
		autoindex on;
		methods POST ;
	}
}

server {
	listen 127.0.0.1:2626;

	root /home/xquah/Desktop/webserv/42-webserv;

	error_page 404 /error_page/404.html;
	client_body_size_buf 100000000;

	location / {
		root /home/xquah/Desktop/webserv/42-webserv;
		index html/sample2.html;
		autoindex on;
		methods GET POST ;
	}
}
