server {
	listen 127.0.0.1:8080;
	server_name server_1;

	root /home/yphang/Desktop/Webserv;

	error_page 404 /error_page/404.html;
	client_max_body_size 100000000;

	location / {
		index sample.html;
		autoindex on;
		methods GET POST;
	}

	location /upload {
		root /home/yphang/Desktop/Webserv/uploads;
		methods POST;
	}

	location /redirect {
		return 301 http://profile-v3.intra.42.fr/;
	}

	location /cgi-bin/ {
		cgi on;
		methods GET POST DELETE;
	}

}